services:
  backend:
    build: ./backend
    env_file:
        - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./backend/static:/app/backend/static
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CI=true

  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/18/docker

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./backend/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path", "/migrations",
        "-database", "postgres://user:password@db:5432/db?sslmode=disable"
      ]
    command: ["up"]

  caddy:
    image: caddy
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data

volumes:
  database_data:
